name = "request-ai"
main = "src/index.ts"
compatibility_date = "2025-02-04"

[ai]
binding = "AI"

[observability]
enabled = true

[vars]
FIREBASE_PROJECT_ID = "web-extention"
CLOUDFLARE_PUBLIC_JWK_CACHE_KEY = "firebase_public_key"

[[kv_namespaces]]
binding = "CLOUDFLARE_PUBLIC_JWK_CACHE_KV"
id = "1ee4a5dd5cd84d5c8407fc4273214ddf"

[[durable_objects.bindings]]
name = "RATE_LIMIT_OBJECT"
class_name = "RateLimitObject"

[[durable_objects.bindings]]
name = "TOKEN_CACHE_OBJECT"
class_name = "TokenCacheObject"

# ここは "追記" で新しいタグにする（既存の v1 は残す）
[[migrations]]
tag = "v2-rate-limit"
new_sqlite_classes = ["RateLimitObject"]

[[migrations]]
tag = "v2-token-cache"
new_sqlite_classes = ["TokenCacheObject"]
