name = "request-ai"
main = "src/index.ts"
compatibility_date = "2025-02-04"

[ai]
binding = "AI"

[observability]
enabled = true

[vars]
FIREBASE_PROJECT_ID = "web-extention"
CLOUDFLARE_PUBLIC_JWK_CACHE_KEY = "firebase_public_key"

[[kv_namespaces]]
binding = "CLOUDFLARE_PUBLIC_JWK_CACHE_KV"
id = "1ee4a5dd5cd84d5c8407fc4273214ddf"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "a4891659d2924553a4ef7a966c66d92c"

[[kv_namespaces]]
binding = "VERIFIED_TOKEN_KV"
id = "88e2485718f44f1e84f283189b0f2133"

[[durable_objects.bindings]]
name = "RATE_LIMIT_OBJECT"
class_name = "RateLimitObject"

# ここは "追記" で新しいタグにする（既存の v1 は残す）
[[migrations]]
tag = "v2-rate-limit"
new_sqlite_classes = ["RateLimitObject"]
